version: 0.2

phases:
  install:
    commands:
      - echo Installing... Running npm install
      - npm install -g mocha
      - npm install
  pre_build:
    commands:
      - echo Pre Build installing unit.js
      - npm install unit.js
  build:
    commands:
      - echo Build started on `date`
      - echo Testing code
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    
    